### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bewisesh91** [KimGrang/w3_solo_project#1]
필수 요구 사항: 프로젝트 관리
- [x] 1. `.env` 파일을 이용해서 민감한 정보(DB 계정 정보, API Key 등)를 관리합니다.
- [x] 2. `.gitignore` 파일을 생성하여 `.env` 파일과 `node_modules` 폴더가 Github에 올라가지 않도록 설정합니다.
- [x] 3. `.prettierrc` 파일을 생성하여 일정한 코드 포맷팅을 유지할 수 있도록 설정합니다.

-----
필수 요구 사항: API 구현하기
 1. 상품 작성 API
- [x] 상품명, 작성 내용, 작성자명, 비밀번호를 **request**에서 전달 받기
- [x] 상품은 두 가지 상태, **판매 중(`FOR_SALE`)및 판매 완료(`SOLD_OUT`)** 를 가질 수 있습니다.
- [x] 상품 등록 시 기본 상태는 **판매 중(`FOR_SALE`)** 입니다.
2. 상품 목록 조회 API
- [x] 상품명, 작성자명, 상품 상태, 작성 날짜 조회하기
- [x] 상품 목록은 작성 날짜를 기준으로 **내림차순(최신순)** 정렬하기
3. 상품 상세 조회 API
- [x] 상품명, 작성 내용, 작성자명, 상품 상태, 작성 날짜 조회하기
4. 상품 정보 수정 API
- [x] 상품명, 작성 내용, 상품 상태, 비밀번호를 **request**에서 전달받기
- [x] 수정할 상품과 비밀번호 일치 여부를 확인한 후, 동일할 때만 글이 **수정**되게 하기
- [x] 선택한 상품이 존재하지 않을 경우, “상품 조회에 실패하였습니다." 메시지 반환하기
5. 상품 삭제 API
- [x] 비밀번호를 **request**에서 전달받기
- [x] 수정할 상품과 비밀번호 일치 여부를 확인한 후, 동일할 때만 글이 **삭제**되게 하기
- [x] 선택한 상품이 존재하지 않을 경우, “상품 조회에 실패하였습니다." 메시지 반환하기

-----
필수 요구 사항
- [ ] AWS EC2 배포

-----

기본 필수 요구 사항 중 프로젝트 관리와 API 구현은 잘하신 것 같아요.
다만, 제출해주신 링크로 접속했을 때 정상적으로 동작하지 않는 것 같은데 한번 확인 부탁 드립니다.

일부 코드에 대해서 피드백을 드리자면, 
현재 products.router.js 파일에 // localhost:3000/api/products POST 이런 주석을 모든 API마다 적어두셨습니다.
사실 로컬 호스트는 정말 '로컬'을 의미하는 것이고 구현하신 API는 배포하신 URL을 통해 동작합니다! : )
따라서, 해당 주석은 삭제해셔도 좋아요! 사실 코드만 보더라도 해당 주석의 내용을 충분히 알 수 있습니다!

또한, 상품 작성 시 상품의 기본 상태는 이미 스키마에서 정의하고 있어요! 
그래서 굳이 const status = 'FOR_SALE' 라고 작성하지 않으셔도 괜찮습니다.

첫 번째 개인 과제인데 충분히 잘하셨습니다.
고생하셨고 다음 과제도 화이팅입니다 👍

**Comment by KimGrang** [comment]
http://54.180.133.187:3000/api/products
https://로 들어갔을 때는 접속되지 않음을 확인했습니다. 
혹시 제가 https://로 링크를 드렸을까요?

**Comment by bewisesh91** [comment]
![image](https://github.com/KimGrang/w3_solo_project/assets/70636283/ab275b48-65e0-4641-a990-9cae188be098)
이렇게 나와요 ㅎㅎㅎ

**Comment by KimGrang** [comment]
pm2에 다시 등록했습니다 
![스크린샷 2024-01-24 102118](https://github.com/KimGrang/w3_solo_project/assets/105832184/011c713a-f3ed-40dc-b71a-36d1a8e6f126)
다시 한번 확인해 주십시오
